### ISSUE TITLE
The Dashboard not detecting prometheus jobs

### ISSUE THREAD

**Issue by elhalouiMed** [cspinetta/kamon-grafana-dashboards#3]
I have a running instance of Prometheus that has one job in the prometheus.yml config file.
The job is correctly monitored in another dashboard but not in this one https://grafana.com/grafana/dashboards/12315

<img width="960" alt="grafana" src="https://user-images.githubusercontent.com/17355991/115638699-2ecfab80-a313-11eb-852c-9edae654c27f.PNG">

here is my configuration on prometheus.yml 

```
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'myApp'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    metrics_path: '/api/kamon/metrics'
    static_configs:
    - targets: ['localhost:9000']
```
Any idea what can cause this issue ?
